version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: "Asia/Riyadh"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
