name = "mas3a-jobs-api"
main = "src/index.js"
compatibility_date = "2026-09-01"

[triggers]
crons = ["*/5 * * * *", "17 * * * *"]


[[ratelimits]]
name = "API_RATE_LIMITER"
namespace_id = "93015401"

  [ratelimits.simple]
  limit = 120
  period = 60

[[ratelimits]]
name = "WRITE_RATE_LIMITER"
namespace_id = "93015402"

  [ratelimits.simple]
  limit = 5
  period = 60

[[d1_databases]]
binding = "DB"
database_name = "mas3a-jobs"
database_id = "997d7aca-b536-4e0b-b412-7065719699ac"
migrations_dir = "migrations"

[vars]
CORS_ORIGIN = "https://mas3a.pages.dev"

[ai]
binding = "AI"

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
